version: '3.4'

services:

  api:
    container_name: feedfin-api
    build: ./backend
    volumes:
      - './backend:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      - FEEDFIN_DEV=true
      - FEEDFIN_PORT=5000
      - FEEDFIN_HOST=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/feedfin_dev
    depends_on:
      - db
    links:
      - db

  db:
    container_name: feedfin-db
    build: ./database
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
